import type { components } from "../../app/api/generated/schema";

export type Recipe = components["schemas"]["Recipe"];
export type RecipeDetail = components["schemas"]["RecipeDetail"];
export type RecipePage = components["schemas"]["RecipePage"];
export type BulkArchiveResponse = components["schemas"]["RecipeBulkArchiveResponse"];
export type RecipeWrite = components["schemas"]["RecipeWrite"];
export type IngredientWrite = components["schemas"]["IngredientWrite"];
export type Job = components["schemas"]["Job"];
export type JobAccepted = components["schemas"]["JobAccepted"];
export type RecipeProcessingSummary = components["schemas"]["RecipeProcessingSummary"];
export type ResolvedNutrition = components["schemas"]["ResolvedNutrition"];
export type NutritionCorrectionWrite = components["schemas"]["NutritionCorrectionWrite"];
export type NutritionState = components["schemas"]["NutritionState"];
export type RecipeCollection = components["schemas"]["RecipeCollection"];
export type RecipeOrganizationWrite = components["schemas"]["RecipeOrganizationWrite"];
export type ImportPreview = components["schemas"]["ImportPreview"];
export type ImportConfirmWrite = components["schemas"]["ImportConfirm"];
export type ImportConfirmComponent = NonNullable<ImportConfirmWrite["components"]>[number];
export type ImportConfirmIngredient = NonNullable<ImportConfirmComponent["ingredients"]>[number];
export type ImportMergeWrite = components["schemas"]["ImportMerge"];
export type ImportPreviewSection = ImportPreview["sections"][number];
export type ImportPreviewIngredient = ImportPreviewSection["ingredients"][number];
export type DuplicateSummary = ImportPreview["duplicates"][number];
export type RecipePhotoAttachWrite = components["schemas"]["RecipePhotoAttach"];
export type ThumbnailCrop = components["schemas"]["ThumbnailCrop"];
export type ThumbnailCropWrite = ThumbnailCrop;
